#!/usr/bin/env sh

# Define plugin name and version
version="2.44.1"
app="gh"
repo="https://github.com/cli/cli"
file="gh_${version}_linux_amd64.tar.gz"
url="${repo}/releases/download/v${version}/${file}"

location="$XDG_APP_HOME/${app}/${version}"
archive="$XDG_APP_HOME/${app}/.archive"

# Check if the executable already exists in the installation directory
if [ -x "$location/bin/task" ]; then
    echo "Executable already exists in installation directory. Skipping build."
else
    # Create necessary directories
    mkdir -p "$location"
    mkdir -p "$archive"

    # Check if the archive file exists
    if [ ! -f "$archive/$file" ]; then
        # Download tar to archive
        wget -P "$archive" "$url"

        # Check if wget was successful
        if [ $? -ne 0 ]; then
            echo "Failed to download $url"
            exit 1
        fi
    else
        echo "Archive file already exists, skipping download."
    fi

    # Extract and link
    tar -xf "$archive/$file" -C "$location" --strip-components=1
fi

# Setup links
exec="$location/bin/$app"

$exec completion -s zsh > $XDG_DATA_HOME/zsh/completions/_$app
ln -sf $exec $XDG_BIN_HOME/$app