#!/usr/bin/env bash

# datasette + sqlite-utils

# Define the array of packages
packages=(
    "python"
    "poetry"
    "ripgrep"
    "fd"
    "bat"
    "cmake"
    "dasel"
    "jq"
    "portal"
    "eza"
    "neovim"
    "lazygit"
    "sqlite"
    "pipx"
    "golang"
    "rust"
    "rust-analyzer"
)

for package in "${packages[@]}"; do
    echo "Installing and setting $package to the latest version..."

    asdf plugin add $package || true  # continue even if the plugin is already added

    asdf install $package latest
    asdf global $package latest

    echo "$package has been successfully installed and set to the latest version."
done

pipx_packages=(
    "datasette"
    "sqlite-utils"
    "httpie"
)

for package in "${pipx_packages[@]}"; do
    echo "Installing and setting $package to the latest version..."

    pipx install $package

    echo "$package has been successfully installed and set to the latest version."
done

echo "All packages have been installed and set to the latest versions."