#!/usr/bin/env bash

# Define plugin name and version
version="23.10"
app="helix"
repo="https://github.com/helix-editor/helix"
file="helix-${version}-x86_64-linux.tar.xz"
url="${repo}/releases/download/${version}/${file}"

location="$XDG_APP_HOME/${app}/${version}"
archive="$XDG_APP_HOME/${app}/.archive"

# Check if the executable already exists in the installation directory
if [ -x "$location/bin/hx" ]; then
    echo "Executable already exists in installation directory. Skipping build."
else
    # Create necessary directories
    mkdir -p "$location"
    mkdir -p "$archive"

    # Check if the archive file exists
    if [ ! -f "$archive/$file" ]; then
        # Download tar to archive
        wget -P "$archive" "$url"

        # Check if wget was successful
        if [ $? -ne 0 ]; then
            echo "Failed to download $url"
            exit 1
        fi
    else
        echo "Archive file already exists, skipping download."
    fi

    # Extract and link
    tar -xf "$archive/$file" -C "$location" --strip-components=1
fi

# Setup links
ln -sf "$location/hx" "$XDG_BIN_HOME/hx"
