#!/usr/bin/env bash

SCRIPT_DIR=$(dirname "$0")

sudo apt -y update && sudo apt -y upgrade

# Basic setup for building python
sudo apt -y update && sudo apt -y upgrade && sudo apt install -y \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    llvm \
    libffi-dev \
    liblzma-dev

# Link wsl config to default location
sudo ln -sf $SCRIPT_DIR/config/wsl.conf /etc/wsl.conf

# Source bootstrap scripts
. $SCRIPT_DIR/setup-zsh
