#!/usr/bin/env zsh

# if pyenv is loaded ignore this file
if type pyenv &> /dev/null; then
  return
fi

# Setup pyenv and remove functions from the global scope
_init_pyenv() {
  unset -f pyenv _init_pyenv

  if [[ ! "$PATH" == */.pyenv/bin* ]]; then
    export PATH="$HOME/.pyenv/bin:$PATH"
  fi
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"

}

# Alias function to initialize pyenv when called
pyenv() {
  _init_pyenv
  pyenv "$@"
}
