#!/bin/sh

if _is_loaded "ASDF_LOADED"; then
  logger "INFO" "asdf is already loaded"

  return 1
fi

# Find where asdf should be installed
ASDF_DIR="${ASDF_DIR:-$XDG_APP_HOME/asdf}"
ASDF_COMPLETIONS="$ASDF_DIR/completions"

# Check if asdf is already installed and find the current version
if [ -d "$ASDF_DIR" ]; then
    CURRENT_VERSION=$(cd $ASDF_DIR && git describe --tags)
else
    CURRENT_VERSION=""
fi

# Fetch the latest version of asdf
LATEST_VERSION=$(curl -s https://api.github.com/repos/asdf-vm/asdf/tags | grep 'name' | head -1 | cut -d '"' -f 4)
if [ -z "$LATEST_VERSION" ]; then
    logger "ERROR" "Unable to fetch the latest version of asdf."

    return 0
fi

# Compare current and latest versions, and update if necessary
if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
    logger "DEBUG" "Updating asdf from $CURRENT_VERSION to $LATEST_VERSION..."

    git -C $HOME/.asdf fetch && git -C $HOME/.asdf checkout $LATEST_VERSION
else
    logger "INFO" "asdf is already up-to-date with version $CURRENT_VERSION."
fi

# Load command
if [[ -f "$ASDF_DIR/asdf.sh" ]]; then
  source "$ASDF_DIR/asdf.sh"

  # Load completions
  if [[ -f "$ASDF_COMPLETIONS/_asdf" ]]; then
    fpath+=("$ASDF_COMPLETIONS")
    autoload -Uz _asdf
    compdef _asdf asdf # compdef is already loaded before loading plugins
  fi
fi

logger "INFO" "asdf finished loading"

ASDF_LOADED=1
