#!/usr/bin/env zsh

# Certificate
export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt

# ---------------------------------------------------------------------------- 
# ENVS
#
# Environment variables to set for zsh session
# ---------------------------------------------------------------------------- 
export _BASE_ARCHIVES="${XDG_CACHE_HOME}/archives"


# ----------------------------------------------------------------------------
# PATHS
#
# Specify paths for user environment
# ----------------------------------------------------------------------------
_in_env ${XDG_BIN_HOME} ${PATH} || _prependenv PATH "${XDG_BIN_HOME}"


# ----------------------------------------------------------------------------
# CONDA PATHS 
#
# Take control over go environment by specifying conda paths
# ----------------------------------------------------------------------------

condarc="${XDG_APP_HOME}/conda/etc/profile.d/conda.sh"
if [ -f "${condarc}" ]; then
  export CONDARC="${XDG_CONFIG_HOME}/.condarc"
  export CONDA_PKGS_DIRS="${_BASE_HOME}/.conda/pkgs"
  export CONDA_ENVS_PATH="${_BASE_HOME}/.conda/envs"

  source "${condarc}"
fi

# ----------------------------------------------------------------------------
# GO PATHS 
#
# Take control over go environment by specifying GO paths
# ----------------------------------------------------------------------------
if (command -v go > /dev/null); then
  export GOROOT="${XDG_APP_HOME}/go/current"
  export GOPATH="${XDG_CACHE_HOME}/go"
  export GOBIN="${XDG_BIN_HOME}"

  # GHQ check
  if (command -v ghq > /dev/null); then
    export GHQ_ROOT="${_BASE_HOME}/dev"
  fi

  # _in_env ${GOPATH} ${PATH} || _prependenv PATH "${GOPATH}/bin"
fi

# ---------------------------------------------------------------------------- 
# DOCKER
#
# Export PATH and other variables that needs to be set
# ---------------------------------------------------------------------------- 

# Check if we are using WSL (meaning we have a windows docker deamon listening)
if [[ $(uname -r) =~ Microsoft ]]; then
  export DOCKER_HOST="tcp://localhost:2375"
fi

# ---------------------------------------------------------------------------- 
# Hooks
# ---------------------------------------------------------------------------- 
if (command -v direnv > /dev/null); then
  eval "$(direnv hook zsh)"
fi

# ---------------------------------------------------------------------------- 
# FINALIZE
#
# Export PATH and other variables that needs to be set
# ---------------------------------------------------------------------------- 
export PATH
