#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- 
# ENVS
#
# Environment variables to set for zsh session
# ---------------------------------------------------------------------------- 
export _BASE_ARCHIVES="${XDG_CACHE_HOME}/archives"
export XDG_APP_HOME="${_BASE_HOME}/opt"


# ----------------------------------------------------------------------------
# PATHS
#
# Specify paths for user environment
# ----------------------------------------------------------------------------
_in_env ${XDG_BIN_HOME} ${PATH} || _prependenv PATH "${XDG_BIN_HOME}"


# ----------------------------------------------------------------------------
# CONDA PATHS 
#
# Take control over go environment by specifying conda paths
# ----------------------------------------------------------------------------
export CONDARC="${XDG_CONFIG_HOME}/.condarc"
export CONDA_PKGS_DIRS="${_BASE_HOME}/.conda/pkgs"
export CONDA_ENVS_PATH="${_BASE_HOME}/.conda/envs"

source "${_BASE_HOME}/opt/conda/current/etc/profile.d/conda.sh"


# ----------------------------------------------------------------------------
# GO PATHS 
#
# Take control over go environment by specifying GO paths
# ----------------------------------------------------------------------------
export GOROOT="${XDG_APP_HOME}/go/current"
export GOPATH="${XDG_APP_HOME}/go/package"
export GHQ_ROOT="${_BASE_HOME}/dev"

_in_env ${GOPATH} ${PATH} || _prependenv PATH "${GOPATH}/bin"


# ---------------------------------------------------------------------------- 
# FINALIZE
#
# Export PATH and other variables that needs to be set
# ---------------------------------------------------------------------------- 
export PATH
