#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- 
# OVERRIDES
# ---------------------------------------------------------------------------- 

export REZ_REPO_PAYLOAD_DIR="${XDG_CACHE_HOME}/archives"


# ---------------------------------------------------------------------------- 
# SOURCE
# ---------------------------------------------------------------------------- 

source "${_BASE_OPT}/conda/base/etc/profile.d/conda.sh"


# ---------------------------------------------------------------------------- 
# PATH MANIPULATION
# ---------------------------------------------------------------------------- 

# HOME BIN -------------------------------------------------------------------
_in_env ${XDG_BIN_HOME} ${PATH} || _prependenv PATH "${XDG_BIN_HOME}"


# GO PATHS -------------------------------------------------------------------
export GOROOT="${_BASE_OPT}/go/base"
export GOBIN="${_BASE_OPT}/go/bin"
export GOPATH="${_BASE_OPT}/go/src"
export GHQ_ROOT="${_BASE_HOME}/dev"


# PIPSI----------------------------------------------------------------------- 
export PIPSI_HOME="${_BASE_OPT}/pipsi"
export PIPSI_BIN_DIR="$(readlink -f ${PIPSI_HOME}/bin)"
if [ -d "${PIPSI_BIN_DIR}" ]; then
  _in_env ${PIPSI_BIN_DIR} ${PATH} || _prependenv PATH "${PIPSI_BIN_DIR}"
fi


# USR PATHS ------------------------------------------------------------------
paths=(
  go/bin
  go/base/bin
  nodejs/bin
  nodejs/base/bin
  fzf/bin
  kitty/bin
  redpen/bin 
  texlive/2018/bin/x86_64-linux 
)

for p in ${paths[@]}; do
  add=$(readlink -f "${_BASE_OPT}/${p}")
  # Don't Do anything if the diectory doesn't exist
  if [ -d "${add}" ]; then
    # If already in PATH ignore
    _in_env ${add} ${PATH} || _prependenv PATH "${add}"
  fi
done


# ---------------------------------------------------------------------------- 
# FINALIZE
# ---------------------------------------------------------------------------- 

export PATH
