#!/usr/bin/env zsh

# Define a function to clone a Git repository and handle folder creation
function dev-clone {
    # Extract the git host, username, and repo name from the repository URL
    local repo_url=$1

    if [[ $repo_url == http* ]] ; then
        local git_host=${repo_url#*//}
        git_host=${git_host%%/*}
        local repo_name=${repo_url##*/}
        repo_name=${repo_name%%.*}
        local git_user=${repo_url#*//}
        git_user=${git_user#*${git_host}/}
        git_user=${git_user%%/*}
    else
        local git_host=${${repo_url#*@}%%:*}
        local git_user=${${repo_url#*:}%%/*}
        local repo_name=${${repo_url##*/}%.*}
    fi

    # Define the directory to clone the repository into
    local dev_dir="${_DEV_HOME}/$git_host/$git_user"
    
    # Create the directory if it doesn't exist
    if [[ ! -d "$dev_dir" ]]; then
        mkdir -p "$dev_dir"
    fi

    # Clone the repository into the directory
    git clone "$repo_url" "$dev_dir/$repo_name"
}


dev-clone $@