#!/usr/bin/env bash

if _is_wsl; then
    cd ~
fi

# Check if CUSTOM_SHELL_SETUP is set
if [[ -n "$CUSTOM_SHELL_SETUP" ]]; then
    sudo apt -y update && sudo apt -y upgrade && sudo apt install -y \
        ripgrep \
        fd-find \
        fzf
fi
